### ISSUE TITLE
Create issues to track progress

### ISSUE THREAD

**Issue by yungyuc** [cfmc30/FDCT#2]
Could you please create GitHub issues to track the work you planned in [the proposal](https://github.com/yungyuc/nsdhw_24au/blob/master/project/cfmc30/README.rst)?  It's OK to deviate a little bit from the plan, but it's important to know how far we go.

**Comment by cfmc30** [comment]
Thanks for your suggestions, #4 created for tracking progress.

**Comment by cfmc30** [comment]
Issue created

**Comment by yungyuc** [comment]
LGTM
